-- =========================
-- TABLES D'ASSOCIATION
-- =========================
DROP TABLE Reparation CASCADE CONSTRAINTS;
DROP TABLE Travaille_Dans_La_Boutique CASCADE CONSTRAINTS;
DROP TABLE Est_Affectee_A CASCADE CONSTRAINTS;
DROP TABLE Pratique_Soins CASCADE CONSTRAINTS;
DROP TABLE Bien_Etre_Quotidien CASCADE CONSTRAINTS;
DROP TABLE Est_Le_Parent_De CASCADE CONSTRAINTS;
DROP TABLE Est_Compatible_Avec CASCADE CONSTRAINTS;
DROP TABLE A_Acces_A CASCADE CONSTRAINTS;
DROP TABLE Est_Parraine CASCADE CONSTRAINTS;
DROP TABLE Chiffre_Affaires CASCADE CONSTRAINTS;

-- =========================
-- TABLES PRINCIPALES DEPENDANTES
-- =========================
DROP TABLE Animal CASCADE CONSTRAINTS;
DROP TABLE Enclos CASCADE CONSTRAINTS;
DROP TABLE Boutique CASCADE CONSTRAINTS;
DROP TABLE Zone CASCADE CONSTRAINTS;
DROP TABLE Contrat_Travail CASCADE CONSTRAINTS;
DROP TABLE Visiteur CASCADE CONSTRAINTS;

-- =========================
-- TABLES PRINCIPALES
-- =========================
DROP TABLE Prestataire CASCADE CONSTRAINTS;
DROP TABLE Prestation CASCADE CONSTRAINTS;
DROP TABLE Parrainage CASCADE CONSTRAINTS;
DROP TABLE Espece CASCADE CONSTRAINTS;
DROP TABLE Personnel CASCADE CONSTRAINTS;
DROP TABLE Fonction CASCADE CONSTRAINTS;