SELECT B.NOM_BOUTIQUE, SUM(CA1.MONTANT) FROM BOUTIQUE B, CHIFFRE_AFFAIRES CA1 WHERE B.ID_BOUTIQUE = CA1.ID_BOUTIQUE GROUP BY B.NOM_BOUTIQUE HAVING SUM(CA1.MONTANT) > (SELECT AVG(SUM(CA2.MONTANT)) FROM CHIFFRE_AFFAIRES CA2 GROUP BY CA2.ID_BOUTIQUE); 

SELECT NOM_ZONE, SUM(CA.MONTANT) FROM ZONE Z, BOUTIQUE B, Chiffre_Affaires CA WHERE Z.ID_ZONE = B.ID_ZONE AND B.ID_BOUTIQUE = CA.ID_BOUTIQUE GROUP BY Z.NOM_ZONE ORDER BY Z.NOM_ZONE; 

SELECT P.NOM, COUNT(S.DATE_SOIN) FROM PERSONNEL P, SOIN S WHERE P.ID_PERSONNEL = S.ID_SOIGNEUR GROUP BY P.NOM;

SELECT E.NOM_ESPECE, AVG(A.POIDS) FROM ESPECE E, ANIMAL A WHERE E.ID_ESPECE = A.ID_ESPECE GROUP BY E.NOM_ESPECE HAVING COUNT(A.ID_ANIMAL) >= 3; 

SELECT A.NOM_ANIMAL, A.POIDS FROM ANIMAL A WHERE A.POIDS > (SELECT AVG(POIDS)FROM ANIMAL);

SELECT P1.NOM FROM PERSONNEL P1 JOIN PERSONNEL P2 ON P1.ID_SUPERIEUR = P2.ID_PERSONNEL AND P1.SALAIRE > P2.SALAIRE; 

SELECT V.NOM_VISITEUR FROM VISITEUR V JOIN EST_PARRAINE EP ON EP.ID_VISITEUR = V.ID_VISITEUR GROUP BY V.NOM_VISITEUR HAVING COUNT(DISTINCT EP.ID_ANIMAL) = (SELECT COUNT(*) FROM ANIMAL); 
SELECT V.NOM_VISITEUR FROM VISITEUR V WHERE NOT EXISTS (SELECT A.ID_ANIMAL FROM ANIMAL A WHERE NOT EXISTS (SELECT EP.ID_ANIMAL FROM EST_PARRAINE EP WHERE V.ID_VISITEUR = EP.ID_VISITEUR AND EP.ID_ANIMAL = A.ID_ANIMAL)); 
SELECT V.NOM_VISITEUR FROM VISITEUR V WHERE NOT EXISTS (SELECT A.ID_ANIMAL FROM ANIMAL A MINUS (SELECT EP.ID_ANIMAL FROM EST_PARRAINE EP WHERE EP.ID_VISITEUR = V.ID_VISITEUR)); 

SELECT P.NOM FROM PERSONNEL P JOIN BOUTIQUE B ON P.ID_PERSONNEL = B.ID_MANAGER UNION (SELECT P.NOM FROM PERSONNEL P JOIN ZONE Z ON P.ID_PERSONNEL = Z.ID_MANAGER); 

SELECT ES.NOM_ESPECE, COUNT(*) FROM ESPECE ES JOIN ANIMAL A ON ES.ID_ESPECE = A.ID_ESPECE JOIN ENCLOS E ON A.LONGITUDE_ENCLOS = E.LONGITUDE AND A.LATITUDE_ENCLOS = E.LATITUDE GROUP BY ES.NOM_ESPECE HAVING COUNT(DISTINCT E.ID_ZONE) > 1; 

SELECT V.NOM_VISITEUR FROM EST_PARRAINE EP JOIN ANIMAL A ON EP.ID_ANIMAL = A.ID_ANIMAL JOIN ESPECE E ON E.ID_ESPECE = A.ID_ESPECE JOIN VISITEUR V ON EP.ID_VISITEUR = V.ID_VISITEUR AND E.Est_Menacee = 1 GROUP BY V.NOM_VISITEUR HAVING COUNT(DISTINCT E.ID_ESPECE) = (SELECT COUNT(*) FROM ESPECE WHERE EST_MENACEE=1); 
SELECT V.NOM_VISITEUR FROM VISITEUR V WHERE NOT EXISTS (SELECT E.ID_ESPECE FROM ESPECE E WHERE E.EST_MENACEE = 1 AND NOT EXISTS (SELECT EP.ID_ANIMAL FROM EST_PARRAINE EP JOIN ANIMAL A ON EP.ID_ANIMAL = A.ID_ANIMAL WHERE A.ID_ESPECE = E.ID_ESPECE AND EP.ID_VISITEUR = V.ID_VISITEUR)); 
SELECT V.NOM_VISITEUR FROM VISITEUR V WHERE NOT EXISTS (SELECT E.ID_ESPECE FROM ESPECE E WHERE E.EST_MENACEE = 1 MINUS (SELECT E.ID_ESPECE FROM ESPECE E JOIN ANIMAL A ON E.ID_ESPECE = A.ID_ESPECE JOIN EST_PARRAINE EP ON A.ID_ANIMAL = EP.ID_ANIMAL AND EP.ID_VISITEUR = V.ID_VISITEUR)); 


SELECT ID_Personnel, Nom, Prenom
FROM Personnel MINUS
    (   
            SELECT ID_Soigneur AS ID_Personnel, P.Nom, P.Prenom FROM Soin S JOIN Personnel P ON P.ID_Personnel = S.ID_Soigneur
        UNION 
            SELECT ID_Veterinaire AS ID_Personnel, P.Nom, P.Prenom FROM Soin S JOIN Personnel P ON P.ID_Personnel = S.ID_Veterinaire
        UNION 
            SELECT R.ID_Personnel, P.Nom, P.Prenom FROM Reparation R JOIN Personnel P ON P.ID_Personnel = R.ID_Personnel
        UNION
            SELECT Z.ID_Manager, P.Nom, P.Prenom FROM Zone Z JOIN Personnel P ON P.ID_Personnel = Z.ID_Manager
        UNION
            SELECT B.ID_Manager, P.Nom, P.Prenom FROM Boutique B JOIN Personnel P ON P.ID_Personnel = B.ID_Manager
        UNION
            SELECT TDB.ID_Personnel, P.Nom, P.Prenom FROM Travaille_Dans_La_Boutique TDB JOIN Personnel P ON TDB.ID_Personnel = P.ID_Personnel
    );
